default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: let_me_try_development

test:
  <<: *default
  database: let_me_try_test

production:
  <<: *default
  database: let_me_try_production
  username: let_me_try
  password: <%= ENV['LET_ME_TRY_DATABASE_PASSWORD'] %>
